[project]
name = "hitchenv-orji"
version = "0.0.0"
requires-python = ">=3.14.0"
dependencies = ["hitchpylibrarytoolkit==0.7.1"]

#[tool.uv.sources]
#hitchpylibrarytoolkit = { path = "../hitchpylibrarytoolkit", editable = true }
